steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ci-cd-pipeline-405011/github.com/wowmind/simple-terraform-cloudrun:91d55389cd480656d692775193588a8b33214448', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ci-cd-pipeline-405011/github.com/wowmind/simple-terraform-cloudrun:91d55389cd480656d692775193588a8b33214448']
# Deploy to cloud run 
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_SERVICE_NAME}', '--image', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}', '--region', 'us-central1', '--platform', 'managed', "--allow-unauthenticated"]
